#!/usr/bin/env python3

# Optionsbleed proof of concept test
# by Hanno Böck
# modified by avelardi to take a filename argument
#usage: optionsbleed [filepath]

import urllib3
import re
from tqdm import tqdm
from multiprocessing import Pool

def test_bleed(url):
    r = pool.request('OPTIONS', url)
    try:
        allow = str(r.headers["Allow"])
    except KeyError:
        return False
    if re.match("^[a-zA-Z]+(-[a-zA-Z]+)? *(, *[a-zA-Z]+(-[a-zA-Z]+)? *)*$", allow):
        z = [x.strip() for x in allow.split(',')]
        if len(z) > len(set(z)):
            print("[duplicates] %s: %s" % (url, repr(allow)))
    elif re.match("^[a-zA-Z]+(-[a-zA-Z]+)? *( +[a-zA-Z]+(-[a-zA-Z]+)? *)+$", allow):
        print("[spaces] %s: %s" % (url, repr(allow)))
    else:
        print("[bleed] %s: %s" % (url, repr(allow)))
    return True

def worker(h):
  #IPv6 catch
  if ":" in h:
    h = '[{}]'.format(h)
  for prefix in ['http://', 'https://']:
    try:
      test_bleed(prefix+h)
    except:
      return

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
pool = urllib3.PoolManager(10, cert_reqs='CERT_NONE')
hl = [x.strip() for x in open(sys.argv[1],'r').read().split('\n')]

try:
  with Pool(10) as p:
      r = list(tqdm(p.imap(worker,hl), total=len(hl)))
      p.close()
      p.join()
except KeyboardInterrupt:
  print("Goodbye")
